### ISSUE TITLE
CDN and NPM module won't load

### ISSUE THREAD

**Issue by CraigglesO** [webtorrent/webtorrent.io#117]
**What version of WebTorrent?**
version - 0.98.18
**What operating system and Node.js version?**
OS X Sierra - Node v7.10.0
**What browser and version? (if using WebTorrent in the browser)**
Tried both Firefox and Chrome [Version 58.0.3029.110 (64-bit)], both latest versions.

[this codepen works](http://codepen.io/yciabaud/full/XdOeWM/)
but the video doesn't show, it just downloads the whole file.

error I get:
`GET https://webtorrent.io/torrents/Sintel/Sintel.mp4 net::ERR_CONTENT_LENGTH_MISMATCH`
``

**Comment by feross** [comment]
Thanks for posting this issue. It's resolved now. The webtorrent.io server had run out of disk space. I only had log rotation set up for the node.js server logs. I'm setting it up for the nginx logs as well now. Cheers!
