### ISSUE TITLE
Do not autoplay if video is not onscreen

### ISSUE THREAD

**Issue by noffle** [webtorrent/webtorrent.io#122]
webtorrent.io exhibits the nefarious "mysterious audio syndrome": I was introducing someone to bittorrent clients via webtorrent.io, and the sintel video starting playing while they were scrolled down the page, producing audio that wasn't immediately identifiable. It would be swell if the video player only automatically played if the player element is onscreen.

Thanks for making webtorrent! :heart: :wave:

**Comment by feross** [comment]
Browsers are starting to block this, including the latest Safari and Chrome. So this issue has solved itself in a way 😆 

In fact, the browsers actually block the autoplay entirely if the video is not muted, which is causing the homepage video to stop working entirely in Chrome 66.

See: https://github.com/webtorrent/webtorrent.io/issues/128
