### ISSUE TITLE
Cannot download this torrent !

### ISSUE THREAD

**Issue by misha-marinenko-official** [webtorrent/webtorrent.io#133]
![image](https://user-images.githubusercontent.com/40549120/45256998-41398880-b3a7-11e8-92bd-4be56ed7f12c.png)
![image](https://user-images.githubusercontent.com/40549120/45256999-4565a600-b3a7-11e8-849c-61eafe47f51a.png)

http://rgho.st/92zqF8KZC - torrent file

Another files are downloading...

![image](https://user-images.githubusercontent.com/40549120/45257012-7940cb80-b3a7-11e8-9d0d-443e2922ce6c.png)

**Comment by rom1504** [comment]
Do not use WebTorrent for copyright infringement.
