### ISSUE TITLE
Add Hubzilla To F.A.Q.

### ISSUE THREAD

**Issue by Francewhoa** [webtorrent/webtorrent.io#139]
About this page https://webtorrent.io/faq

Under "Who is using WebTorrent today?" section, I suggest to add this new item:

* **[Hubzilla](https://hubzilla.org)** - WebTorrent player integration into posts ([source code](https://github.com/demitas-ace/wtplayer/tree/master/wtplayer))

Any volunteer? I would be happy to contribute testing of https://webtorrent.io/faq

**Comment by feross** [comment]
Can you send a pull request to the `webtorrent` repo?

**Comment by feross** [comment]
Ah, I see you already did. Okay, closing this issue.
